remote_theme: broccolini/swiss
title: Leo D.
description: A Personal Website
#twitter: "oqtavios"
baseurl: ""
#username: oqtavios
#user_title: Leo D.
theme_color: yellow
social_link: twitter
social_username: oqtavios
github_username: oqtavios
